### PR TITLE
Only get slot data for slots that are whitelisted

### PR DESCRIPTION
**Pull request by raman325**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:

### CODE REVIEW

**Comment by firstof9** [comment]
You think this'll fix #248 ?

**Comment by labanx** [comment]
teste the updated __init__ file against #248 , and it stopped pulling the wrong keyslots, but it doesn't pull the correct ones either.
```
2021-11-03 15:35:46 DEBUG (MainThread) [custom_components.keymaster] Finished fetching keymaster data in 0.000 seconds (success: True)
2021-11-03 15:35:51 DEBUG (MainThread) [custom_components.keymaster] Finished fetching keymaster data in 0.000 seconds (success: True)
2021-11-03 15:35:56 DEBUG (MainThread) [custom_components.keymaster] Finished fetching keymaster data in 0.000 seconds (success: True)
2021-11-03 15:36:01 DEBUG (MainThread) [custom_components.keymaster] Finished fetching keymaster data in 0.000 seconds (success: True)
````

While it before pulled the 5 first keyslots (since i only enabled 5)

**Comment by raman325** [comment]
@labanx can you see the other slots in zwavejs2mqtt? Based on what you are saying, it seems like the driver is only returning the first five slots.

**Comment by labanx** [comment]
> @labanx can you see the other slots in zwavejs2mqtt? Based on what you are saying, it seems like the driver is only returning the first five slots.

@raman325 
Yup, i could even set the pin in keymaster. I just have to force the automation, but keymaster doesn't think it's added.
But it shows up in zwavejs2mqtt and i can also see it in the zwave-js debug logs

image

image


```
2021-11-03T16:11:40.762Z DRIVER » [Node 031] [REQ] [SendDataBridge]
                                  │ source node id:   1
                                  │ transmit options: 0x25
                                  │ route:            0, 0, 0, 0
                                  │ callback id:      86
                                  └─[SecurityCCCommandEncapsulation]
                                    │ nonce id: 146
                                    └─[UserCodeCCSet]
                                        user id:   12
                                        id status: Enabled
                                        user code: 77668877
```

**Comment by smiller171** [comment]
I think merging this could be really helpful in reducing the z-wave traffic generated by keymaster

**Comment by firstof9** [comment]
This will likely need re-basing after #277 is merged.

**Comment by smiller171** [comment]
@firstof9 #277 is merged. Is there anything I can do to help get this merged in? The sheer number of requests keymaster is trying to send to my old Yale lock is causing me a lot of problems.

**Comment by firstof9** [comment]
Note the only zwave traffic that is generated is when a code is being cleared or set.

**Pull request closed without merging**
