### PR TITLE
fix: add FE599 lock 'user access' code to `alarmType` map

### LINKED ISSUE #281: ISSUE: FE599 locks not notifying on events
**Describe the bug**
FE599 locks --> When locking/unlocking via code and/or manual, no notify events are being triggered and sent to mobile device.
Works fine for BE649ZP locks

**Environment (please complete the following information):**
image
image

- Z-Wave integration name: zwaveJS
- Lock make and model: FE599

**Logs**
Paste your error logs here.

**Screenshots**
none available to show

### PR DESCRIPTION
**Pull request by firstof9**
## Proposed change

Adds FE599 'User Access' code to `alarmType` map
Fix tests, remove python 3.8 from tests and adds python 3.10

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #281

### CODE REVIEW

**Comment by firstof9** [comment]
Ignore the HACS validation failure, this will fix that as well.

**Comment by fireheadman** [comment]
Ready to test when you when you are

**Comment by firstof9** [comment]
update to `v0.0.80` and give it a whirl.

**Comment by fireheadman** [comment]
updated, restarted HA.   tested out lock/unlocked by button and entered code.
neither of these methods triggered a notification.    

unsure if there is anything else I need to perform after applying the update to v0.0.80

**Comment by firstof9** [comment]
Double check the notifications make sure either `<doorname>_lock_notifications` is on or that the notifications are on for the code slot.

Also see if the event `keymaster_lock_state_changed` fires when you do anything with the lock too.

**Comment by fireheadman** [comment]
notifications are on (per screenshot)
image
image
image
image

showing the automation last triggered
image

**Comment by fireheadman** [comment]
Also went through the 'configure' process once more.    No change... no notifications for either FE599.

**Comment by firstof9** [comment]
Any `keymaster_lock_state_changed` events when you do anything to that lock?

**Comment by fireheadman** [comment]
absolutely nothing reporting in the developer --> events (zwave_js_notification)

and this is the Z-WaveJS Logs showing a code entered to unlock the door

image

**Comment by firstof9** [comment]
`keymaster_lock_state_changed` not `zwave_js_notification` totally different events

**Comment by firstof9** [comment]
here's an example:

```json
{
    "event_type": "keymaster_lock_state_changed",
    "data": {
        "notification_source": "event",
        "lockname": "frontdoor",
        "entity_id": "lock.kwikset_touchpad_electronic_deadbolt_frontdoor",
        "state": "locked",
        "action_text": "Manual lock operation",
        "code_slot": 0,
        "code_slot_name": ""
    },
    "origin": "LOCAL",
    "time_fired": "2022-06-01T00:54:25.335310+00:00",
    "context": {
        "id": "01G4EC3CSQB64ENPFCYK45VHGW",
        "parent_id": null,
        "user_id": null
    }
}
```

**Comment by fireheadman** [comment]
nothing when listening to this event
did a code to unlock, also pressed the lock button on the door.
image

**Comment by fireheadman** [comment]
and for reference... I did the same for my BE649ZP lock just to see the content like you gave.
image

**Comment by firstof9** [comment]
Ooof these FE599s :disappointed:

**Pull request merged**
