### PR TITLE
Add zwave_js support

### PR DESCRIPTION
**Pull request by raman325**
## Breaking change
Hopefully nothing, but it would be good for someone to pull down this branch to their HA instance and verify

## Proposed change
Add `zwave_js` support. Theoretically adds support for lock state change events for `zwave_js` too but:
1) Something may have broken on the `zwave_js` side that prevents us from seeing these events at the moment.
2) I was unable to test the logic because of said issue

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:

### CODE REVIEW

**Comment by johnnyl6** [comment]
So today the HA team announced their deprecation of zwave and the new zwave_js integration. I think it's worth for keymaster to focus on zwave_js support for now, and gradually phase out openzwave which will not be out of beta in HA.


After migration to zwave_js in HA. I am unable to pick alarm level entity.  Which one to choose for alarm type?

image


image

**Comment by raman325** [comment]
and the purpose of this PR is to add zwave_js support to keymaster, so I think we are on the same page here 🙂 did you use the version of keymaster that's available on HACS or this branch? The current version on HACS does not work with zwave_js.

Also of note, with zwave_js, there is no user_code/access_control sensor, instead there's an event that gets fired, so when this does get released, you won't see those options on the form

**Comment by johnnyl6** [comment]
@raman325 I used your pull request branch. I uninstalled the hacs version and added your repository manually, then installed from hacs. Is it correct? Or do I need to download a copy of this PR and manually install?

**Comment by raman325** [comment]
You will need to download a copy of this PR and manually install. If you add my repository manually, you will pull from the main branch which doesn't include the zwave_js changes

**Comment by johnnyl6** [comment]
> You will need to download a copy of this PR and manually install. If you add my repository manually, you will pull from the main branch which doesn't include the zwave_js changes

ok, downloaded a zip and did a manual install. Configured as below There are some erros in the log. Log file attached
[log.txt](https://github.com/FutureTense/keymaster/files/5927602/log.txt)



image

**Comment by raman325** [comment]
thanks for testing @johnnyl6 this is a known bug in `zwave-js-server`. A new version of the official addon was released, if you are using that and update it should be resolved. If you are using z2m you will have to wait, the version hasn't been bumped yet

**Comment by johnnyl6** [comment]
Updated my zwave_js addon to latest and installed the latest code https://github.com/FutureTense/keymaster/pull/74/commits/ce46c51019b799792df2f72b6d6e69edcc3fd7db

Got some errors in log
[log.txt](https://github.com/FutureTense/keymaster/files/5928117/log.txt)

Existing PINs display as connected but can't be updated. Tried to create PIN in new slot but status stuck at connecting.

**Comment by raman325** [comment]
thanks @johnnyl6 just pushed a fix for that, can you try again with the latest?

**Comment by johnnyl6** [comment]
> thanks @johnnyl6 just pushed a fix for that, can you try again with the latest?

Just did. No apparent errors in log  but newly created PIN is stuck at connecting.
[log.txt](https://github.com/FutureTense/keymaster/files/5928451/log.txt)

**Comment by raman325** [comment]
does the state of `sensor.<lockname>_code_slot_<codeslot#>` match your input pin? If not, what's in the state?

**Comment by johnnyl6** [comment]
I have 3 existing PINs and their corresponding sensor entities state all matching the PIN. The 4th PIN is the newly created, state is empty

**Comment by raman325** [comment]
ah, do you have an entity for `input_boolean.allow_automation_execution`? If so, turn that on, then try disabling and re-enabling the pin.

I need to add a new asset file for zwave_js because the current automations for that input_boolean don't work

**Comment by johnnyl6** [comment]
Got an error in the zwave_js asset file, related to automation?

2021-02-04 13:36:06 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: not a valid value for dictionary value @ data['event']. Got None. (See ?, line ?).

**Comment by raman325** [comment]
used the wrong key, try now (and thanks for going through these iterations with me)

**Comment by johnnyl6** [comment]
No problem glad to help. Updated the zwave_js.yaml. Got new error: 

Edit: missing one line in the end. now added.
`
2021-02-04 14:28:49 INFO (MainThread) [custom_components.keymaster] Version v0.0.0 is starting, if you have any issues please report them here: https://github.com/FutureTense/keymaster
2021-02-04 14:28:49 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry frontdoor for keymaster
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/keymaster/__init__.py", line 129, in async_setup_entry
primary_lock, child_locks = await generate_keymaster_locks(hass, config_entry)
File "/config/custom_components/keymaster/helpers.py", line 148, in generate_keymaster_locks
client = hass.data[ZWAVE_JS_DOMAIN][lock_config_entry_id][
KeyError: 'e961461237ef1328d13cae5c580aed45'
`

**Comment by raman325** [comment]
is there more to the log? looks cut off at the end

**Comment by raman325** [comment]
did you remove the zwave_js integration? If it's still there, is the entity ID correct? That error says that it can't find the zwave_js client where it expects which should only occur if the integration was removed or the entity ID is referencing a different lock

**Comment by johnnyl6** [comment]
@raman325 Awesome work! I uninstalled the integration and reinstall kemaster. It's fully working now including my long desired notification! PIN codes are synching too. Will keep testing other features but the major functionalities are ready. I strongly advise the PR to be approved. 👍🎉😜

**Comment by raman325** [comment]
sweet! thanks again for your tests, we will likely merge this soon

**Pull request merged**
