### PR TITLE
Hot reload package files if possible when keymaster.generate_package service is called, and add notifications for processes that take a while

### PR DESCRIPTION
**Pull request by raman325**
## Proposed change
As long as all the platforms that we use in keymaster template files (automation, input_boolean, input_number, input_text, script_domain, template_domain) are loaded, we can call their `reload` services to update entities without requiring a Home Assistant restart. This change attempts to reload each platform, and if it can't, that means a full restart is required. A notification is created telling the user whether they need to do anything or not.

Bonus points - I was able to remove all the logic to remove entities during options updates and entry unload and use the reload services logic instead. That was a lot of somewhat delicate code that is no longer needed. The downside to this approach is that it can take longer to unload. As such, I added an auto dismissed notification so the user knows something is happening.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:

### CODE REVIEW

**Comment by firstof9** [comment]
Looks like we need to adjust the manifest file for this as well.

**Comment by firstof9** [comment]
Test resulted in error:
`ERROR    homeassistant.config_entries:config_entries.py:331 Error unloading entry frontdoor for keymaster`

```txt
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/homeassistant/config_entries.py", line 321, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/home/runner/work/keymaster/keymaster/custom_components/keymaster/__init__.py", line 240, in async_unload_entry
    await async_create(
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by raman325** [comment]
where'd you see that?

**Comment by firstof9** [comment]
When I re-ran the test, but it looks like it ran it against the old commit.

**Comment by raman325** [comment]
thanks, finally got it resolved

**Comment by raman325** [comment]
~~we should hold off on merging this until the package shrinking changes, which will get rid of sensor.date and sensor.time references (they can't be reloaded)~~

EDIT: Resolved this with the last commit

**Pull request merged**
