### PR TITLE
Initial zwave_js support

### PR DESCRIPTION
**Pull request by raman325**
## Proposed change
WIP support for `zwave_js`. Requires upstream support in HA, some changes to `zwave-js-server-python`, and a more thorough review, but I wanted to get a draft out there so you could get an early peek at the logic and provide feedback.

TODO:
- [ ] Add tests
- [ ] Look at reducing repeat code by building more helpers
- [ ] Add a new asset to create `allow_execution` for `zwave_js`
- [x] Verify that all of this actually works once zwave_js is live

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:

### CODE REVIEW

**Comment by firstof9** [comment]
Here's hoping zwave-js handles code slots better than ozw 👍

**Review by FutureTense — COMMENTED** [review]
@firstof9 does release drafter have to be installed before this can be merged?

**Comment by raman325** [comment]
This can't be merged until the next HA release at a minimum, it won't work until that happens

**Comment by firstof9** [comment]
> @firstof9 does release drafter have to be installed before this can be merged?

The release drafter stuff only deals in the workflow stuff for github, nothing that would halt a merge.

**Comment by firstof9** [comment]
Tests will fail until 2021.2.0 drops.

**Pull request merged**
