### PR TITLE
Handle event changes in 2021.4

### PR DESCRIPTION
**Pull request by raman325**
## Breaking change
Moves minimum HA version up to 2021.4 due to breaking change in the `zwave_js` integration.

## Proposed change
Updates to handle downstream changes

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:

### CODE REVIEW

**Comment by hanerd** [comment]
Just a quick note, using this on 2021.04b4 and child locks doesn’t seem to be working. 

Whenever I add the path for my child locks file, it doesn’t seem to take and the path is cleared out in the integration config.

**Comment by raman325** [comment]
> Just a quick note, using this on 2021.04b4 and child locks doesn’t seem to be working.
> 
> Whenever I add the path for my child locks file, it doesn’t seem to take and the path is cleared out in the integration config.

Was it working with the current version of the integration on 2021.3.4? At this point, child locks don't even do anything, but the behavior you described is weird

**Comment by hanerd** [comment]
> Was it working with the current version of the integration on 2021.3.4? At this point, child locks don't even do anything, but the behavior you described is weird

It didn't do anything, but the path did remain in the configuration.  I actually updated to 2021.04b4 to check out if this would make it work.  😄   I just discovered the project a couple days ago.

**Comment by raman325** [comment]
> > Was it working with the current version of the integration on 2021.3.4? At this point, child locks don't even do anything, but the behavior you described is weird
> 
> It didn't do anything, but the path did remain in the configuration. I actually updated to 2021.04b4 to check out if this would make it work. 😄 I just discovered the project a couple days ago.

Can you open an issue for this so I can track it? I'm going to release this so that the rest of the functionality continues to work in 2021.4

**Pull request merged**
