### PR TITLE
Update notify prefix

### LINKED ISSUE #201: ISSUE: Notifications not working based on example
**Describe the bug**
I am having a hard time getting notifications to fire. In my troubleshooting, I discovered that the config in the autogenerated keymaster_common.yaml may have a discrepancy on the following lines:
https://github.com/FutureTense/keymaster/blob/main/custom_components/keymaster/keymaster_common.yaml#L154
https://github.com/FutureTense/keymaster/blob/main/custom_components/keymaster/keymaster_common.yaml#L174
https://github.com/FutureTense/keymaster/blob/main/custom_components/keymaster/keymaster_common.yaml#L190
I believe `LOCKNAME_manual_notify` should be replaced with `keymaster_LOCKNAME_manual_notify`.

The wiki and tests would need to be updated to follow suit.
https://github.com/FutureTense/keymaster/wiki/Notification-Example-Script
https://github.com/FutureTense/keymaster/blob/main/tests/yaml/frontdoor/frontdoor_keymaster_common.yaml

**Environment (please complete the following information):**

- OS: [e.g. HassOS/Raspbian/CentOS] **Home Assistant OS 6.1**
- Type of system that HA is running on: [e.g. RPi3/NUC/Synology] **RPi4**
- Home Assistant version: [e.g. 0.105.5] **2021.7.3**
- Hassio/Docker/Core? **Hassio**
- Component version: [e.g. 0.1.2] **0.0.55**
- Z-Wave integration name: [e.g. zwave_js] **zwave_js**
- Lock make and model: [e.g. Schlage BE469] **Schlage BE469**

**Logs**
Paste your error logs here.

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

### PR DESCRIPTION
**Pull request by srpomeroy**
## Breaking change

This change fixes the notify scripts to all have the prefix "keymaster". This ensures notifications can be defined easily on a per lock basis and makes it easy to identify the integration to which the script block belongs.

## Proposed change

Standardize the naming of the notification names.
Fix for #201 

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [x] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #201 
- This PR is related to issue: #201

### CODE REVIEW

**Comment by srpomeroy** [comment]
I skipped updating the tests for now as they appear to be a few revisions behind the current code base.

**Review by firstof9 — APPROVED** [review]
Changes look good.

EDIT: Requesting 2nd set of eyes for review

**Comment by raman325** [comment]
this is fine, but since script.LOCKNAME_manual_notify is created by the user, the user's workflow will break if they regenerate package files without making the requisite change to their script name. We will need to mention this in big bold letters in the release. We will also need to update https://github.com/FutureTense/keymaster/wiki/Notification-Example-Script when this is merged

**Review by raman325 — APPROVED** [review]

**Comment by firstof9** [comment]
The `breaking-change` flag should put it under the breaking changes release note item so that should be fine.
We'll need to include a quip about adding the prefix to their notify script.

**Comment by secabeen** [comment]
Is action needed if you haven't setup any notification scripts?

**Comment by firstof9** [comment]
No but you will get the warning message stating it cannot find the script to run. (safe to ignore it)

**Pull request merged**
