### PR TITLE
Correct typo in call to "keymaster_{lockname}_copy_from_parent_{x}"

### LINKED ISSUE #319: ISSUE: Child locks do not seem to work...
First, thanks for creating Keymaster. I have been using it for ~2 years (with a single lock on a different install).

I am running Keymaster 0.0.83, Z-Wave JS UI 1.5.0, and HA 2023.1.6.

I am trying to add 3 locks, 2 of them parents of the first. They are all Kwikset Home Connect 620s.

When I start adding the child locks, I get errors (like described in https://github.com/FutureTense/keymaster/issues/304).

The difference is that none of the child locks seem to be getting the pins.

### PR DESCRIPTION
**Pull request by asveikau**
## Proposed change

Add missing keymaster_ prefix which was leading to an error.  Verified locally to fix the issue for me.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

- This PR fixes or closes issue: fixes #319 and #304.

### CODE REVIEW

**Comment by asveikau** [comment]
After looking at #304 maybe that's actually distinct, it has `keymaster_` at the start.  However I can confirm this fixes an issue for me (#319 ?)

**Review by firstof9 — APPROVED** [review]
Good catch, thanks!

**Comment by heyitsyang** [comment]
After installing this upgrade, on boot I get:

```
Logger: homeassistant.helpers.service
Source: helpers/service.py:637
First occurred: 8:43:57 AM (4 occurrences)
Last logged: 8:43:57 AM

Unable to find referenced entities automation.copy_front_door_accesscount_back_door_1, automation.copy_front_door_accesslimit_back_door_1, automation.copy_front_door_daterange_back_door_1, automation.copy_front_door_enabled_back_door_1, automation.copy_front_door_end_date_back_door_1, automation.copy_front_door_fri_back_door_1, automation.copy_front_door_fri_end_date_back_door_1, automation.copy_front_door_fri_inc_back_door_1, automation.copy_front_door_fri_start_date_back_door_1, automation.copy_front_door_mon_back_door_1, automation.copy_front_door_mon_end_date_back_door_1, automation.copy_front_door_mon_inc_back_door_1, automation.copy_front_door_mon_start_date_back_door_1, automation.copy_front_door_name_back_door_1, automation.copy_front_door_notify_back_door_1, automation.copy_front_door_pin_back_door_1, automation.copy_front_door_reset_back_door_1, automation.copy_front_door_sat_back_door_1, automation.copy_front_door_sat_end_date_back_door_1, automation.copy_front_door_sat_inc_back_door_1, automation.copy_front_door_sat_start_date_back_door_1, automation.copy_front_door_start_date_back_door_1, automation.copy_front_door_sun_back_door_1, automation.copy_front_door_sun_end_date_back_door_1, automation.copy_front_door_sun_inc_back_door_1, automation.copy_front_door_sun_start_date_back_door_1, automation.copy_front_door_thu_back_door_1, automation.copy_front_door_thu_end_date_back_door_1, automation.copy_front_door_thu_inc_back_door_1, automation.copy_front_door_thu_start_date_back_door_1, automation.copy_front_door_tue_back_door_1, automation.copy_front_door_tue_end_date_back_door_1, automation.copy_front_door_tue_inc_back_door_1, automation.copy_front_door_tue_start_date_back_door_1, automation.copy_front_door_wed_back_door_1, automation.copy_front_door_wed_end_date_back_door_1, automation.copy_front_door_wed_inc_back_door_1, automation.copy_front_door_wed_start_date_back_door_1 or it is/they are currently not available
Unable to find referenced entities automation.copy_front_door_accesscount_back_door_2, automation.copy_front_door_accesslimit_back_door_2, automation.copy_front_door_daterange_back_door_2, automation.copy_front_door_enabled_back_door_2, automation.copy_front_door_end_date_back_door_2, automation.copy_front_door_fri_back_door_2, automation.copy_front_door_fri_end_date_back_door_2, automation.copy_front_door_fri_inc_back_door_2, automation.copy_front_door_fri_start_date_back_door_2, automation.copy_front_door_mon_back_door_2, automation.copy_front_door_mon_end_date_back_door_2, automation.copy_front_door_mon_inc_back_door_2, automation.copy_front_door_mon_start_date_back_door_2, automation.copy_front_door_name_back_door_2, automation.copy_front_door_notify_back_door_2, automation.copy_front_door_pin_back_door_2, automation.copy_front_door_reset_back_door_2, automation.copy_front_door_sat_back_door_2, automation.copy_front_door_sat_end_date_back_door_2, automation.copy_front_door_sat_inc_back_door_2, automation.copy_front_door_sat_start_date_back_door_2, automation.copy_front_door_start_date_back_door_2, automation.copy_front_door_sun_back_door_2, automation.copy_front_door_sun_end_date_back_door_2, automation.copy_front_door_sun_inc_back_door_2, automation.copy_front_door_sun_start_date_back_door_2, automation.copy_front_door_thu_back_door_2, automation.copy_front_door_thu_end_date_back_door_2, automation.copy_front_door_thu_inc_back_door_2, automation.copy_front_door_thu_start_date_back_door_2, automation.copy_front_door_tue_back_door_2, automation.copy_front_door_tue_end_date_back_door_2, automation.copy_front_door_tue_inc_back_door_2, automation.copy_front_door_tue_start_date_back_door_2, automation.copy_front_door_wed_back_door_2, automation.copy_front_door_wed_end_date_back_door_2, automation.copy_front_door_wed_inc_back_door_2, automation.copy_front_door_wed_start_date_back_door_2 or it is/they are currently not available
Unable to find referenced entities automation.copy_front_door_accesscount_back_door_3, automation.copy_front_door_accesslimit_back_door_3, automation.copy_front_door_daterange_back_door_3, automation.copy_front_door_enabled_back_door_3, automation.copy_front_door_end_date_back_door_3, automation.copy_front_door_fri_back_door_3, automation.copy_front_door_fri_end_date_back_door_3, automation.copy_front_door_fri_inc_back_door_3, automation.copy_front_door_fri_start_date_back_door_3, automation.copy_front_door_mon_back_door_3, automation.copy_front_door_mon_end_date_back_door_3, automation.copy_front_door_mon_inc_back_door_3, automation.copy_front_door_mon_start_date_back_door_3, automation.copy_front_door_name_back_door_3, automation.copy_front_door_notify_back_door_3, automation.copy_front_door_pin_back_door_3, automation.copy_front_door_reset_back_door_3, automation.copy_front_door_sat_back_door_3, automation.copy_front_door_sat_end_date_back_door_3, automation.copy_front_door_sat_inc_back_door_3, automation.copy_front_door_sat_start_date_back_door_3, automation.copy_front_door_start_date_back_door_3, automation.copy_front_door_sun_back_door_3, automation.copy_front_door_sun_end_date_back_door_3, automation.copy_front_door_sun_inc_back_door_3, automation.copy_front_door_sun_start_date_back_door_3, automation.copy_front_door_thu_back_door_3, automation.copy_front_door_thu_end_date_back_door_3, automation.copy_front_door_thu_inc_back_door_3, automation.copy_front_door_thu_start_date_back_door_3, automation.copy_front_door_tue_back_door_3, automation.copy_front_door_tue_end_date_back_door_3, automation.copy_front_door_tue_inc_back_door_3, automation.copy_front_door_tue_start_date_back_door_3, automation.copy_front_door_wed_back_door_3, automation.copy_front_door_wed_end_date_back_door_3, automation.copy_front_door_wed_inc_back_door_3, automation.copy_front_door_wed_start_date_back_door_3 or it is/they are currently not available
Unable to find referenced entities automation.copy_front_door_accesscount_back_door_4, automation.copy_front_door_accesslimit_back_door_4, automation.copy_front_door_daterange_back_door_4, automation.copy_front_door_enabled_back_door_4, automation.copy_front_door_end_date_back_door_4, automation.copy_front_door_fri_back_door_4, automation.copy_front_door_fri_end_date_back_door_4, automation.copy_front_door_fri_inc_back_door_4, automation.copy_front_door_fri_start_date_back_door_4, automation.copy_front_door_mon_back_door_4, automation.copy_front_door_mon_end_date_back_door_4, automation.copy_front_door_mon_inc_back_door_4, automation.copy_front_door_mon_start_date_back_door_4, automation.copy_front_door_name_back_door_4, automation.copy_front_door_notify_back_door_4, automation.copy_front_door_pin_back_door_4, automation.copy_front_door_reset_back_door_4, automation.copy_front_door_sat_back_door_4, automation.copy_front_door_sat_end_date_back_door_4, automation.copy_front_door_sat_inc_back_door_4, automation.copy_front_door_sat_start_date_back_door_4, automation.copy_front_door_start_date_back_door_4, automation.copy_front_door_sun_back_door_4, automation.copy_front_door_sun_end_date_back_door_4, automation.copy_front_door_sun_inc_back_door_4, automation.copy_front_door_sun_start_date_back_door_4, automation.copy_front_door_thu_back_door_4, automation.copy_front_door_thu_end_date_back_door_4, automation.copy_front_door_thu_inc_back_door_4, automation.copy_front_door_thu_start_date_back_door_4, automation.copy_front_door_tue_back_door_4, automation.copy_front_door_tue_end_date_back_door_4, automation.copy_front_door_tue_inc_back_door_4, automation.copy_front_door_tue_start_date_back_door_4, automation.copy_front_door_wed_back_door_4, automation.copy_front_door_wed_end_date_back_door_4, automation.copy_front_door_wed_inc_back_door_4, automation.copy_front_door_wed_start_date_back_door_4 or it is/they are currently not available
```

**Comment by firstof9** [comment]
Have you regenerated your scripts?

**Comment by heyitsyang** [comment]
I've now regenerated the scripts.  It didn't help.  Under what conditions do the scripts need to be regenerated?

I can see entities similar to the ones noted in the log as missing, but mine are
automation.keymaster_copy_front_door_accesscount_back_door_1 etc.

In fact, all of my automation entities have the word keymaster in them.

**Pull request merged**
